"""child pin_hash

Revision ID: 9fc198c7efc4
Revises: d6dd2094417e
Create Date: 2026-06-22 16:34:54.976324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fc198c7efc4'
down_revision: Union[str, Sequence[str], None] = 'd6dd2094417e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('pin_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child', 'pin_hash')
    # ### end Alembic commands ###
