"""baseline catalog

Revision ID: a165f2d2bbf3
Revises: 
Create Date: 2026-06-21 00:50:15.109249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a165f2d2bbf3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantined_extraction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pdf_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantined_extraction_pdf_sha256'), 'quarantined_extraction', ['pdf_sha256'], unique=False)
    op.create_table('skill',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_key')
    )
    op.create_index(op.f('ix_skill_skill_key'), 'skill', ['skill_key'], unique=False)
    op.create_table('worksheet',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worked_example', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_pdf_r2_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('problem_count', sa.Integer(), nullable=False),
    sa.Column('pdf_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pdf_sha256')
    )
    op.create_index(op.f('ix_worksheet_pdf_sha256'), 'worksheet', ['pdf_sha256'], unique=False)
    op.create_index(op.f('ix_worksheet_skill_id'), 'worksheet', ['skill_id'], unique=False)
    op.create_table('problem',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worksheet_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['worksheet_id'], ['worksheet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_worksheet_id'), 'problem', ['worksheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problem_worksheet_id'), table_name='problem')
    op.drop_table('problem')
    op.drop_index(op.f('ix_worksheet_skill_id'), table_name='worksheet')
    op.drop_index(op.f('ix_worksheet_pdf_sha256'), table_name='worksheet')
    op.drop_table('worksheet')
    op.drop_index(op.f('ix_skill_skill_key'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_quarantined_extraction_pdf_sha256'), table_name='quarantined_extraction')
    op.drop_table('quarantined_extraction')
    # ### end Alembic commands ###
