"""guidance_session and tutor_turn

Revision ID: bc4b678c9d0e
Revises: 9fc198c7efc4
Create Date: 2026-06-22 18:38:21.063382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc4b678c9d0e'
down_revision: Union[str, Sequence[str], None] = '9fc198c7efc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guidance_session',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('problem_result_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entry_point', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_tier_reached', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('scan_attached', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['problem_result_id'], ['problem_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guidance_session_attempt_id'), 'guidance_session', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_guidance_session_child_id'), 'guidance_session', ['child_id'], unique=False)
    op.create_index(op.f('ix_guidance_session_problem_id'), 'guidance_session', ['problem_id'], unique=False)
    op.create_index(op.f('ix_guidance_session_problem_result_id'), 'guidance_session', ['problem_result_id'], unique=False)
    op.create_table('tutor_turn',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visuals', sa.JSON(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['guidance_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_turn_session_id'), 'tutor_turn', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tutor_turn_session_id'), table_name='tutor_turn')
    op.drop_table('tutor_turn')
    op.drop_index(op.f('ix_guidance_session_problem_result_id'), table_name='guidance_session')
    op.drop_index(op.f('ix_guidance_session_problem_id'), table_name='guidance_session')
    op.drop_index(op.f('ix_guidance_session_child_id'), table_name='guidance_session')
    op.drop_index(op.f('ix_guidance_session_attempt_id'), table_name='guidance_session')
    op.drop_table('guidance_session')
    # ### end Alembic commands ###
